//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImageConverter.Lib.Lang {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ImageConverter.Lib.Lang.lang", typeof(lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CancelButton {
            get {
                return ResourceManager.GetString("CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wether or not to delete the original image.
        /// </summary>
        public static string DeleteImageDesc {
            get {
                return ResourceManager.GetString("DeleteImageDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Image.
        /// </summary>
        public static string DeleteImageTitle {
            get {
                return ResourceManager.GetString("DeleteImageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Converted.
        /// </summary>
        public static string HeaderConverted {
            get {
                return ResourceManager.GetString("HeaderConverted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string HeaderLocation {
            get {
                return ResourceManager.GetString("HeaderLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string HeaderName {
            get {
                return ResourceManager.GetString("HeaderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        public static string HeaderSize {
            get {
                return ResourceManager.GetString("HeaderSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string HeaderType {
            get {
                return ResourceManager.GetString("HeaderType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wether or not to play a sound when finished converting.
        /// </summary>
        public static string PlaySoundDesc {
            get {
                return ResourceManager.GetString("PlaySoundDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play Sound.
        /// </summary>
        public static string PlaySoundTite {
            get {
                return ResourceManager.GetString("PlaySoundTite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Converter.
        /// </summary>
        public static string ProgramTitle {
            get {
                return ResourceManager.GetString("ProgramTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string ResetButton {
            get {
                return ResourceManager.GetString("ResetButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The sound that plays at the end of the conversion.
        /// </summary>
        public static string SoundToPlayDesc {
            get {
                return ResourceManager.GetString("SoundToPlayDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sound.
        /// </summary>
        public static string SoundToPlayTite {
            get {
                return ResourceManager.GetString("SoundToPlayTite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whether or not to try and emulate Jpeg size.
        /// </summary>
        public static string WebPEmulateJpegDesc {
            get {
                return ResourceManager.GetString("WebPEmulateJpegDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emulate Jpeg Size.
        /// </summary>
        public static string WebPEmulateJpegTitle {
            get {
                return ResourceManager.GetString("WebPEmulateJpegTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whether or not to use lossless compression.
        /// </summary>
        public static string WebPLossessDesc {
            get {
                return ResourceManager.GetString("WebPLossessDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lossless.
        /// </summary>
        public static string WebPLossessTitle {
            get {
                return ResourceManager.GetString("WebPLossessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The quality of the compression.
        /// </summary>
        public static string WebPQualityDesc {
            get {
                return ResourceManager.GetString("WebPQualityDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quality.
        /// </summary>
        public static string WebPQualityTitle {
            get {
                return ResourceManager.GetString("WebPQualityTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whether or not to remove the alpha channel/layer.
        /// </summary>
        public static string WebPRemoveAlphaDesc {
            get {
                return ResourceManager.GetString("WebPRemoveAlphaDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Alpha.
        /// </summary>
        public static string WebPRemoveAlphaTitle {
            get {
                return ResourceManager.GetString("WebPRemoveAlphaTitle", resourceCulture);
            }
        }
    }
}
