//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConverterUtilities.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ConverterUtilities.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert.
        /// </summary>
        public static string ConvertButton {
            get {
                return ResourceManager.GetString("ConvertButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Converted.
        /// </summary>
        public static string Converted {
            get {
                return ResourceManager.GetString("Converted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Converter.
        /// </summary>
        public static string ImageHeader {
            get {
                return ResourceManager.GetString("ImageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximize.
        /// </summary>
        public static string Maximize {
            get {
                return ResourceManager.GetString("Maximize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string MenuClear {
            get {
                return ResourceManager.GetString("MenuClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimize.
        /// </summary>
        public static string Minimize {
            get {
                return ResourceManager.GetString("Minimize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore.
        /// </summary>
        public static string Restore {
            get {
                return ResourceManager.GetString("Restore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are updates. Click here to go to the download page..
        /// </summary>
        public static string RightWindowDownloadToolTip {
            get {
                return ResourceManager.GetString("RightWindowDownloadToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Bugs and Request Features.
        /// </summary>
        public static string RightWindowGithubToolTip {
            get {
                return ResourceManager.GetString("RightWindowGithubToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string RightWindowSettingsToolTip {
            get {
                return ResourceManager.GetString("RightWindowSettingsToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for updates.
        /// </summary>
        public static string RightWindowUpdateToolTip {
            get {
                return ResourceManager.GetString("RightWindowUpdateToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string SettingsCancel {
            get {
                return ResourceManager.GetString("SettingsCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup Files.
        /// </summary>
        public static string SettingsCreatTemp {
            get {
                return ResourceManager.GetString("SettingsCreatTemp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Backup after conversion.
        /// </summary>
        public static string SettingsDeleteTemp {
            get {
                return ResourceManager.GetString("SettingsDeleteTemp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images.
        /// </summary>
        public static string SettingsImageHeader {
            get {
                return ResourceManager.GetString("SettingsImageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quality:.
        /// </summary>
        public static string SettingsJpegQualityLabel {
            get {
                return ResourceManager.GetString("SettingsJpegQualityLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lossless.
        /// </summary>
        public static string SettingsPngLossless {
            get {
                return ResourceManager.GetString("SettingsPngLossless", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quality:.
        /// </summary>
        public static string SettingsPngQualityLabel {
            get {
                return ResourceManager.GetString("SettingsPngQualityLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Alpha.
        /// </summary>
        public static string SettingsPngRemoveAlpha {
            get {
                return ResourceManager.GetString("SettingsPngRemoveAlpha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string SettingsReset {
            get {
                return ResourceManager.GetString("SettingsReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string SettingsSave {
            get {
                return ResourceManager.GetString("SettingsSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Videos.
        /// </summary>
        public static string SettingsVideoHeader {
            get {
                return ResourceManager.GetString("SettingsVideoHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VideoHeight:.
        /// </summary>
        public static string SettingsVideoHeight {
            get {
                return ResourceManager.GetString("SettingsVideoHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change VideoWidth and VideoHeight of video.
        /// </summary>
        public static string SettingsVideoSize {
            get {
                return ResourceManager.GetString("SettingsVideoSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VideoWidth:.
        /// </summary>
        public static string SettingsVideoWidth {
            get {
                return ResourceManager.GetString("SettingsVideoWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emulate JPEG Size.
        /// </summary>
        public static string SettingsWebPEmulateJpeg {
            get {
                return ResourceManager.GetString("SettingsWebPEmulateJpeg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lossless.
        /// </summary>
        public static string SettingsWebPLossless {
            get {
                return ResourceManager.GetString("SettingsWebPLossless", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quality:.
        /// </summary>
        public static string SettingsWebPQualityLabel {
            get {
                return ResourceManager.GetString("SettingsWebPQualityLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Alpha.
        /// </summary>
        public static string SettingsWebPRemoveAlpha {
            get {
                return ResourceManager.GetString("SettingsWebPRemoveAlpha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already Converting.
        /// </summary>
        public static string ToastAlreadyConverting {
            get {
                return ResourceManager.GetString("ToastAlreadyConverting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished Converting.
        /// </summary>
        public static string ToastConvertFinished {
            get {
                return ResourceManager.GetString("ToastConvertFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a preview release, some things might not work. Please use this with caution and report any bugs..
        /// </summary>
        public static string ToastPreviewRelease {
            get {
                return ResourceManager.GetString("ToastPreviewRelease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings reset, make sure you save them!.
        /// </summary>
        public static string ToastSettingsReset {
            get {
                return ResourceManager.GetString("ToastSettingsReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings were saved!.
        /// </summary>
        public static string ToastSettingsSaved {
            get {
                return ResourceManager.GetString("ToastSettingsSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to check for update. Please try again..
        /// </summary>
        public static string ToastUpdateCheckFail {
            get {
                return ResourceManager.GetString("ToastUpdateCheckFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is an update for.
        /// </summary>
        public static string ToastUpdatePart1 {
            get {
                return ResourceManager.GetString("ToastUpdatePart1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your version is:.
        /// </summary>
        public static string ToastUpdatePart2 {
            get {
                return ResourceManager.GetString("ToastUpdatePart2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The updated version is:.
        /// </summary>
        public static string ToastUpdatePart3 {
            get {
                return ResourceManager.GetString("ToastUpdatePart3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video conversion can take a long time to finish. Currently progress isn&apos;t shown. It is not recommended that you convert multiple videos at once..
        /// </summary>
        public static string ToastVideoMessage {
            get {
                return ResourceManager.GetString("ToastVideoMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video Converter.
        /// </summary>
        public static string VideoHeader {
            get {
                return ResourceManager.GetString("VideoHeader", resourceCulture);
            }
        }
    }
}
