//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Image_Converter.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Image_Converter.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About the program.
        /// </summary>
        public static string AboutTooltip {
            get {
                return ResourceManager.GetString("AboutTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup.
        /// </summary>
        public static string Backup {
            get {
                return ResourceManager.GetString("Backup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        public static string Browse {
            get {
                return ResourceManager.GetString("Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bug.
        /// </summary>
        public static string Bug {
            get {
                return ResourceManager.GetString("Bug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bug or Feature.
        /// </summary>
        public static string BugContent {
            get {
                return ResourceManager.GetString("BugContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bugs or Features.
        /// </summary>
        public static string BugsOrFeatures {
            get {
                return ResourceManager.GetString("BugsOrFeatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report a Bug or request a feature.
        /// </summary>
        public static string BugsTooltip {
            get {
                return ResourceManager.GetString("BugsTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title:.
        /// </summary>
        public static string BugTitle {
            get {
                return ResourceManager.GetString("BugTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert.
        /// </summary>
        public static string Convert {
            get {
                return ResourceManager.GetString("Convert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start the conversion.
        /// </summary>
        public static string ConvertTooltip {
            get {
                return ResourceManager.GetString("ConvertTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emulate Size Of Jpeg.
        /// </summary>
        public static string EmulateJpeg {
            get {
                return ResourceManager.GetString("EmulateJpeg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string ExitMenu {
            get {
                return ResourceManager.GetString("ExitMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit the application.
        /// </summary>
        public static string ExitTooltip {
            get {
                return ResourceManager.GetString("ExitTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feature.
        /// </summary>
        public static string Feature {
            get {
                return ResourceManager.GetString("Feature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Converted.
        /// </summary>
        public static string FileConverted {
            get {
                return ResourceManager.GetString("FileConverted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Location.
        /// </summary>
        public static string FileLocation {
            get {
                return ResourceManager.GetString("FileLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Name.
        /// </summary>
        public static string FileName {
            get {
                return ResourceManager.GetString("FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Size.
        /// </summary>
        public static string FileSize {
            get {
                return ResourceManager.GetString("FileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Type.
        /// </summary>
        public static string FileType {
            get {
                return ResourceManager.GetString("FileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished with conversion.
        /// </summary>
        public static string FinishedConversion {
            get {
                return ResourceManager.GetString("FinishedConversion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Converter.
        /// </summary>
        public static string ImageConverter {
            get {
                return ResourceManager.GetString("ImageConverter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lossless.
        /// </summary>
        public static string Lossless {
            get {
                return ResourceManager.GetString("Lossless", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open File.
        /// </summary>
        public static string OpenFileMenu {
            get {
                return ResourceManager.GetString("OpenFileMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select and image or images to use.
        /// </summary>
        public static string OpenFileTooltip {
            get {
                return ResourceManager.GetString("OpenFileTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Folder.
        /// </summary>
        public static string OpenFolderMenu {
            get {
                return ResourceManager.GetString("OpenFolderMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open a folder.
        /// </summary>
        public static string OpenFolderTooltip {
            get {
                return ResourceManager.GetString("OpenFolderTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play Sound When Finished.
        /// </summary>
        public static string PlaySound {
            get {
                return ResourceManager.GetString("PlaySound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quality:.
        /// </summary>
        public static string Quality {
            get {
                return ResourceManager.GetString("Quality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Alpha.
        /// </summary>
        public static string RemoveAlpha {
            get {
                return ResourceManager.GetString("RemoveAlpha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset the settings to default settings.
        /// </summary>
        public static string ResetTooltip {
            get {
                return ResourceManager.GetString("ResetTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save the settings.
        /// </summary>
        public static string SaveTooltip {
            get {
                return ResourceManager.GetString("SaveTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opens the settings.
        /// </summary>
        public static string SettingsTooltip {
            get {
                return ResourceManager.GetString("SettingsTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string SubmitBug {
            get {
                return ResourceManager.GetString("SubmitBug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit the bug or feature request.
        /// </summary>
        public static string SubmitTooltip {
            get {
                return ResourceManager.GetString("SubmitTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use A Custom Folder.
        /// </summary>
        public static string UseCustomFolder {
            get {
                return ResourceManager.GetString("UseCustomFolder", resourceCulture);
            }
        }
    }
}
